oauth:
  allowNoAuthorization: false
  allowInvalidAuthorization: false
  verify_api_key_url: 'https://sunilb-trial-test.apigee.net/edgemicro-auth/verifyApiKey'
  public_key: "-----BEGIN CERTIFICATE-----\r\nMIICpDCCAYwCCQCkXgmFq5cvqTANBgkqhkiG9w0BAQsFADAUMRIwEAYDVQQDDAls\r\nb2NhbGhvc3QwHhcNMTcxMjA5MDIyOTU2WhcNMTcxMjEwMDIyOTU2WjAUMRIwEAYD\r\nVQQDDAlsb2NhbGhvc3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCz\r\nB/gZzquZNGgDNnEpaQcSstix36x+VmPX0S0X4B54AWb2bNC2o2cWuvDFQBTv3O/6\r\ncLxsWlX2iTAC4yL3e7NmQ4k03N3eNnbT1XStcEBj4OZ6b65/4EhEtuVtaZdkka7S\r\ni6b+XxAmDCwZEqkNfoY6EIIpUEvSXvTe4iND5BAh0qAp3GrEnQlJRuOuqoA1Hh4J\r\nG+icja6ca0dwM3wojzOCEir0yzjh7IULnt8UcLlUG+E9IcfKOiBTXtIvzQkEUBDT\r\nOYk1tr6aoKXqvLOB9W14Jync6bm1AGXE7hdXOEqxjQVwCDnNOZsueOwmC2LmVG0R\r\nkDJc6avwUZE62itDvW7FAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAIzIRLqhcHiv\r\nj6s02XEhFjnFvsJFLGfFmjibS5Hf0RlY6R36nuS5W3YJ9RTk+7De6RyQtrUfBwrJ\r\n7Aez4MEMbwjGA1jDQajcNGJGiA/4wqU2Xuo4vUPr8GxKkK8kTy0OlY/p+NS7pzTE\r\nFQAE7dI/4aD4iyJ+IaYdfewi8fogOndwPibdge5A2VVrWCEmI7tjOyCX0OU8HCca\r\nbNfVHHImClzVTxVAVhI/K3O4xjuE9RIVpvrHxvFHAW3JkcwPo0KFJF8MVAidWngY\r\nBIYczPvcK7auDgMn0RZ1YnAeFFnGdcnETX2ea0dtF9uaMyrsouE+RLxThnMKqL2n\r\n27ncH1cmM00=\r\n-----END CERTIFICATE-----"
  product_to_proxy: &ref_0
    CurrencyProduct-test:
      - currency-v1
    edgemicro_product:
      - edgemicro-auth
      - edgemicro_hello
    sampleAPI:
      - SampleProxy
    apieatery-sid-sunil:
      - oauth-dev-training
      - secure-backend
  product_to_api_resource: &ref_1
    CurrencyProduct-test: []
    edgemicro_product:
      - /
    sampleAPI: []
    apieatery-sid-sunil: []
    helloworld: []
analytics:
  source: microgateway
  proxy: dummy
  proxy_revision: 1
  compress: false
  flushInterval: 5000
  uri: >-
    https://edgemicroservices.apigee.net/edgemicro/axpublisher/organization/sunilb-trial/environment/test
  bufferSize: 10000
  batchSize: 500
  key: 269d7c40c430ca2e98aac27c1cd30dd0caa77d9fc7162c07dd21d68baabca1bd
  secret: aef7cd1ded1e709ea8a1696c5e5505053e28095c6ee888964f430ccc1908238d
edgemicro:
  port: 8000
  max_connections: 1000
  config_change_poll_interval: 600
  logging:
    level: info
    dir: /var/tmp
    stats_log_interval: 60
    rotate_interval: 24
  plugins:
    sequence:
      - oauth
headers:
  x-forwarded-for: true
  x-forwarded-host: true
  x-request-id: true
  x-response-time: true
  via: true
proxies:
  - max_connections: 1000
    name: edgemicro_hello
    revision: '1'
    proxy_name: default
    base_path: /microhello
    target_name: default
    url: 'http://mocktarget.apigee.net/'
product_to_proxy: *ref_0
product_to_api_resource: *ref_1
quota:
  CurrencyProduct-test:
    allow: '10000'
    interval: '1'
    timeUnit: month
    bufferSize: 10000
    uri: >-
      https://edgemicroservices.apigee.net/edgemicro/quotas/organization/sunilb-trial/environment/test
    key: 269d7c40c430ca2e98aac27c1cd30dd0caa77d9fc7162c07dd21d68baabca1bd
    secret: aef7cd1ded1e709ea8a1696c5e5505053e28095c6ee888964f430ccc1908238d
  edgemicro_product:
    allow: 'null'
    interval: 'null'
    timeUnit: 'null'
    bufferSize: 10000
    uri: >-
      https://edgemicroservices.apigee.net/edgemicro/quotas/organization/sunilb-trial/environment/test
    key: 269d7c40c430ca2e98aac27c1cd30dd0caa77d9fc7162c07dd21d68baabca1bd
    secret: aef7cd1ded1e709ea8a1696c5e5505053e28095c6ee888964f430ccc1908238d
  sampleAPI:
    allow: '10000'
    interval: '1'
    timeUnit: month
    bufferSize: 10000
    uri: >-
      https://edgemicroservices.apigee.net/edgemicro/quotas/organization/sunilb-trial/environment/test
    key: 269d7c40c430ca2e98aac27c1cd30dd0caa77d9fc7162c07dd21d68baabca1bd
    secret: aef7cd1ded1e709ea8a1696c5e5505053e28095c6ee888964f430ccc1908238d
  apieatery-sid-sunil:
    allow: '100'
    interval: '1'
    timeUnit: minute
    bufferSize: 10000
    uri: >-
      https://edgemicroservices.apigee.net/edgemicro/quotas/organization/sunilb-trial/environment/test
    key: 269d7c40c430ca2e98aac27c1cd30dd0caa77d9fc7162c07dd21d68baabca1bd
    secret: aef7cd1ded1e709ea8a1696c5e5505053e28095c6ee888964f430ccc1908238d
